[workspace]
default-members = ["welds", "welds-connections", "welds-macros"]
members = ["welds", "welds-connections", "welds-macros"]
workspace.resolver = "2"

[profile.dev.package.sqlx-macros]
opt-level = 3

